from enum import IntEnum

BAUDRATE = 115200

class OUTPUT_STATES(IntEnum):
    ON = 1
    OFF = 2
    TOGGLE = 3

class SCHUTTER_STATES(IntEnum):
    CLOSE = 1
    OPEN = 2
    STOP = 3
    STEP_MODE = 4

class KEY_MODE(IntEnum):
    NO = 0
    NC = 1

COMMAND_FUNCTION_IN = "I"
COMMAND_FUNCTION_OUT = "O"
COMMAND_FUNCTION_PWM = "LED"
COMMAND_FUNCTION_COVER = "R"
COMMAND_FUNCTION_FIND = "AT+FIND"
COMMAND_FUNCTION_PONG = "PONG"
COMMAND_FUNCTION_PRESS_SHORT = "PS"
COMMAND_FUNCTION_PRESS_LONG = "PL"
COMMAND_FUNCTION_TEMP = "T"
